# Generated by Django 5.2.10 on 2026-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название модели')),
                ('file', models.FileField(upload_to='3d_assets/', verbose_name='3D файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': '3D Модель',
                'verbose_name_plural': '3D Модели',
            },
        ),
    ]
