# Generated by Django 6.0.2 on 2026-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='3d_assets/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
