# Generated by Django 6.0.1 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_asset_options_alter_asset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
    ]