# Generated by Django 5.2 on 2026-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_image_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '3D Модель', 'verbose_name_plural': '3D Модели'},
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('animals', '🐾 Животные'), ('characters', '👥 Персонажи'), ('vehicles', '🚗 Техника'), ('nature', '🌿 Природа'), ('fantasy', '🧙 Фэнтези'), ('other', '📦 Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='3d_assets/', verbose_name='3D файл'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название модели'),
        ),
    ]
