"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # Новый импорт
# Загружаем переменные из .env файла
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Если ключа нет в .env, возьмем запасной (но лучше, чтобы был)
SECRET_KEY = os.getenv('SECRET_KEY', 'unsafe-secret-key')
# os.getenv возвращает строку. Нам нужно превратить строку 'True' в булево True.
DEBUG = os.getenv('DEBUG') == 'True'
# Разрешенные хосты. В продакшене здесь будет имя сайта.
# Звездочка * разрешает всем (пока оставим так для простоты)
ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'gallery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

# Базовый URL для доступа к медиафайлам через браузер
# Если здесь '/media/', то файл будет доступен по адресу:
# http://ваш-сайт/media/3d_assets/ваша-модель.glb
MEDIA_URL = '/media/'

# Абсолютный путь к папке на сервере, где будут храниться медиафайлы
# BASE_DIR - автоматическая переменная Django (корень проекта)
# 'media' - название папки, которая будет создана
MEDIA_ROOT = BASE_DIR / 'media'

# URL, по которому браузер ищет статику
STATIC_URL = 'static/'
# Папки, где мы (разработчики) храним статику
STATICFILES_DIRS = [
BASE_DIR / 'gallery' / 'static',
]
# Папка, куда collectstatic соберет ВСЕ файлы для сервера (создастся сама)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Включаем сжатие и кэширование статики для WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Настройки для авторизации
LOGIN_REDIRECT_URL = 'home'  # Куда идти после входа
LOGOUT_REDIRECT_URL = 'home'  # Куда идти после выхода
LOGIN_URL = 'login'  # Куда идти если не авторизован